# Generated by Django 4.2 on 2023-04-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0003_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/products"),
        ),
    ]
