# Generated by Django 4.2 on 2023-04-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_product1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product1',
        ),
    ]
