# Generated by Django 4.2 on 2023-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='is_read_by_admin',
            field=models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='متن پاسخ تماس با ما'),
        ),
    ]
