# Generated by Django 4.2 on 2023-04-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_module", "0003_profileimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="profileImage",
            new_name="userprofile",
        ),
    ]
